site_name: srs-sdp-integration
site_description: SRS SDP Integration to Cloudeka Service Portal

nav:
  - Home: index.md
  - Introduction: 
      - Purpose of the Document: introduction/purpose-of-the-document.md
  - Description:
      - Product Overview: description/product-overview.md
      - Product Features: description/product-features.md
      - User Documentation: description/documentation.md
  - Interface Requirement:
      - User Interface: interface-requirement/user-interface.md
      - Software Interface: interface-requirement/software-interface.md
      - Communication Interface: interface-requirement/communication-interface.md
  - Functional Requirement:
    - Functional Requirement Table: functional-requirement/functional-requirement-table.md
    - Use Case Diagram: functional-requirement/use-case-diagram.md
    - Use Case Description: functional-requirement/use-case-description.md
  - Non-Functional Requirements:
      - Non-Functional Requirements: non-functional-requirements/non-functional-requirements.md
  - Appendix:
      - Appendix: appendix/appendix.md

theme:
  name: material

plugins:
  - techdocs-core
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css 
